version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "CamerasDB"
      POSTGRES_USER: "superuser"
      POSTGRES_PASSWORD: "4756"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
volumes:
  postgres-data:  
